import pandas as pd  # data handling
from sqlalchemy import create_engine  # MySQL connection

# -------------------------------
# CONNECT TO MYSQL DATABASE
# -------------------------------
# creating connection between Python and MySQL
engine = create_engine(
    "mysql+mysqlconnector://root:Balaji%4012345@localhost/food_delivery_db"
)

# -------------------------------
# LOAD DATA FROM MYSQL TABLE
# -------------------------------
# fetching engineered dataset for analysis
df = pd.read_sql("SELECT * FROM engineered_food_delivery", engine)

# -------------------------------
# BASIC INFORMATION
# -------------------------------
# dataset structure check
print("📊 BASIC INFO")
print("Shape:", df.shape)  # rows and columns count
print("\nColumns:\n", df.columns)  # column names

# -------------------------------
# TOP BUSINESS INSIGHTS
# -------------------------------

# top cities by order count
print("\n🏙 Top Cities")
print(df["city"].value_counts().head())

# most popular cuisines
print("\n🍔 Top Cuisines")
print(df["cuisine_type"].value_counts().head())

# -------------------------------
# KPI (KEY PERFORMANCE INDICATORS)
# -------------------------------

# average order value
print("\n💰 Avg Order Value:", round(df["order_value"].mean(), 2))

# average delivery time
print("\n⏱ Avg Delivery Time:", round(df["delivery_time_min"].mean(), 2))

# cancellation rate calculation
print("\n❌ Cancellation Rate:",
      round((df["order_status"] == "Cancelled").mean() * 100, 2), "%")

# average delivery rating
print("\n⭐ Avg Delivery Rating:",
      round(df["delivery_rating"].mean(), 2))

# peak hour order distribution
print("\n🔥 Peak Hour Orders:")
print(df["peak_hour"].value_counts())

# -------------------------------
# ADVANCED BUSINESS INSIGHTS
# -------------------------------

# revenue generated by each city
print("\n📈 Revenue by City:")
print(df.groupby("city")["order_value"].sum()
      .sort_values(ascending=False).head())

# profit margin by cuisine type
print("\n📉 Profit Margin by Cuisine:")
print(df.groupby("cuisine_type")["profit_margin_percent"].mean()
      .sort_values(ascending=False).head())

# average delivery time per city
print("\n🚚 Delivery Time by City:")
print(df.groupby("city")["delivery_time_min"].mean()
      .sort_values())

# top restaurants with cancellations
print("\n❌ Cancellation by Restaurant:")
print(df[df["order_status"] == "Cancelled"]["restaurant_name"]
      .value_counts().head())